// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9vshwOQmd8_HULainRGsHzXjQ4rLM7_I',
    appId: '1:427188618383:web:73d4a4148e86eb15801cfa',
    messagingSenderId: '427188618383',
    projectId: 'maqueta-mensajes',
    authDomain: 'maqueta-mensajes.firebaseapp.com',
    storageBucket: 'maqueta-mensajes.firebasestorage.app',
    measurementId: 'G-3NTNMLH6YP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGH-2hUJKXuBHQhuDn2uUCJhrZ9aONLLk',
    appId: '1:427188618383:android:7494955787a45fb6801cfa',
    messagingSenderId: '427188618383',
    projectId: 'maqueta-mensajes',
    storageBucket: 'maqueta-mensajes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQMPHd8DqYlrkybwbuvYOjLFwGNWh9SPU',
    appId: '1:427188618383:ios:7ed931699eaba192801cfa',
    messagingSenderId: '427188618383',
    projectId: 'maqueta-mensajes',
    storageBucket: 'maqueta-mensajes.firebasestorage.app',
    iosBundleId: 'com.example.maquetaMensajes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQMPHd8DqYlrkybwbuvYOjLFwGNWh9SPU',
    appId: '1:427188618383:ios:7ed931699eaba192801cfa',
    messagingSenderId: '427188618383',
    projectId: 'maqueta-mensajes',
    storageBucket: 'maqueta-mensajes.firebasestorage.app',
    iosBundleId: 'com.example.maquetaMensajes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9vshwOQmd8_HULainRGsHzXjQ4rLM7_I',
    appId: '1:427188618383:web:68a3832a03b65fce801cfa',
    messagingSenderId: '427188618383',
    projectId: 'maqueta-mensajes',
    authDomain: 'maqueta-mensajes.firebaseapp.com',
    storageBucket: 'maqueta-mensajes.firebasestorage.app',
    measurementId: 'G-LJ2BHVDQBV',
  );

}